<a href="https://colab.research.google.com/github/MichaelYeung2004/pytorch_tytorials/blob/main/1_tensor_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor(张量)

张量（Tensor）是一种特殊的数据结构，与数组和矩阵非常相似。在 PyTorch 中，我们使用张量对模型的输入和输出以及模型的参数进行编码。
张量与 NumPy 的 ndarray 类似，但张量还可以在 GPU 或其他专用硬件上运行，以加速计算。如果你熟悉 ndarray，你会觉得 Tensor API 非常亲切。如果不熟悉，请跟随我们一起快速了解其 API。

In [ ]:
import torch
import numpy as np

## 张量初始化
张量可以通过多种方式进行初始化。请看以下示例：

**直接从数据创建**

张量可以直接从数据创建。其数据类型会被自动推断。

In [ ]:
data = [[1, 2], [3, 4]] # 创建一个2x2的矩阵
x_data = torch.tensor(data) # 创建一个张量
print(x_data)

tensor([[1, 2],
        [3, 4]])


**从 NumPy 数组创建**

张量可以从NumPy数组创建（反之亦然 - 参见[与 NumPy 的桥梁](https://colab.research.google.com/drive/1HLBZiGhLlPuL-E8p2ukAYDjGwHF-pmbU#scrollTo=j2C_zq9WclaG&line=1&uniqifier=1)）。

In [ ]:
np_array = np.array(data) # 将data转换为numpy数组
x_np = torch.from_numpy(np_array) # 将numpy数组转换为张量
print(x_np) # 打印张量

tensor([[1, 2],
        [3, 4]])


**从另一个张量创建：**

新张量会保留参数张量的属性（如形状、数据类型），除非显式地进行重写。

In [ ]:
x_ones = torch.ones_like(x_data) # 保留 x_data 的属性
#使用f-string
print(f"Ones Tensor: \n {x_ones} \n")
#不使用f-string
print("Ones Tensor: \n", x_ones, "\n")
x_rand = torch.rand_like(x_data, dtype=torch.float) # 重写 x_data 的数据类型
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.4104, 0.2227],
        [0.0995, 0.8977]]) 



**使用随机值或常量值创建：**

shape 是一个表示张量维度的元组。在下面的函数中，它决定了输出张量的维度。

In [ ]:
shape = (2, 3,)   # 创建一个2x3的随机张量
rand_tensor = torch.rand(shape) # 创建一个2x3的随机张量
ones_tensor = torch.ones(shape) # 创建一个2x3的全1张量
zeros_tensor = torch.zeros(shape) # 创建一个2x3的全0张量

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.2731, 0.7065, 0.0360],
        [0.4549, 0.9519, 0.1272]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## 张量属性
张量属性描述了它们的形状、数据类型以及存储它们的设备。

In [ ]:
tensor = torch.rand(3, 4) # 创建一个3x4的随机张量

print(f"Shape of tensor: {tensor.shape}") # 打印张量的形状
print(f"Datatype of tensor: {tensor.dtype}") # 打印张量的数据类型
print(f"Device tensor is stored on: {tensor.device}") # 打印张量存储的设备

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## 张量操作
这里有超过 100 种张量操作，包括转置、索引、切片、数学运算、线性代数、随机采样等，官方文档 中有全面的描述。

每一项操作都可以在 GPU 上运行（通常比在 CPU 上运行速度更快）。如果你正在使用 Colab，可以通过“修改 (Edit)” > “笔记本设置 (Notebook Settings)”来分配一个 GPU。

In [ ]:
# 如果有可用的 GPU，我们将张量移动到 GPU 上
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


试用一下列表中的一些操作。如果你熟悉 NumPy API，你会发现 Tensor API 非常易于使用。

**标准的 NumPy 式索引和切片：**

In [ ]:
tensor = torch.ones(4, 4) # 创建一个4x4的全1张量
tensor[:,1] = 0 # 将第2列的所有元素设置为0
print(tensor) # 打印张量

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**连接张量** 你可以使用 torch.cat 沿指定维度连接一系列张量。另请参阅 torch.stack，这是另一种张量连接操作，与 torch.cat 有细微差别。

In [ ]:
t1 = torch.cat([tensor, tensor, tensor], dim=1) # 将三个tensor在第1维度上拼接，dim=1表示在列上拼接，会输出一个4x12的张量
print(t1)
t2 = torch.cat([tensor, tensor, tensor], dim=0) # 将三个tensor在第0维度上拼接，dim=0表示在行上拼接，会输出一个12x4的张量
print(t2)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**张量相乘**

In [ ]:
# 这将计算逐元素的乘积
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# 另一种语法：
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**计算两个张量之间的矩阵乘法**

In [ ]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# 另一种语法：
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


**原地（In-place）操作**

带 _ 后缀的操作是原地操作。例如：x.copy_(y)、x.t_() 会改变 x 的值。

In [ ]:
print(tensor, "\n") # 打印张量
tensor.add_(5) # 将张量中的每个元素都加上5
print(tensor) # 打印张量

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


>**注意**
>原地操作可以节省一些内存，但在计算导数时可能会因为立即丢失历史记录而产生问题。因此，我们不鼓励使用它们。




##与 NumPy 的桥梁
CPU 上的张量和 NumPy 数组可以共享其底层的内存地址，改变其中一个，另一个也会随之改变。

In [ ]:
t = torch.ones(5) # 创建一个5个元素的全1张量
print(f"t: {t}") # 打印张量
n = t.numpy() # 将张量转换为numpy数组
print(f"n: {n}") # 打印numpy数组

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


张量的变化会反映在 NumPy 数组中。

In [ ]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


**NumPy 数组转换为张量**

In [ ]:
n = np.ones(5) # 创建一个5个元素的全1numpy数组
t = torch.from_numpy(n) # 将numpy数组转换为张量

NumPy 数组的变化会反映在张量中。

In [ ]:
np.add(n, 1, out=n) # 将numpy数组中的每个元素都加上1
print(f"t: {t}") # 打印张量
print(f"n: {n}") # 打印numpy数组

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
